// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(BookSalesContext))]
    [Migration("20241011155439_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shared.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorName")
                        .IsUnique()
                        .HasDatabaseName("UX_Author_AuthorName");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Dương Ngọc Hải"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Trần Hiếu Nghĩa"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Tô Hoài"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Tố Hữu"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Nguyễn Trần Phương Tứng"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Hồ Quỳnh Hương"
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Tun Phạm"
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Tuấn Trần"
                        });
                });

            modelBuilder.Entity("Shared.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Shared.Models.BillDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("BookSaleId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("BookSaleId");

                    b.ToTable("BillDetails");
                });

            modelBuilder.Entity("Shared.Models.BookSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UX_BookSale_Title");

                    b.ToTable("BookSales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Price = 120000.0,
                            Quantity = 1000,
                            Title = "Đường Hầm Mùa Hạ Tập 1"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Price = 120000.0,
                            Quantity = 1500,
                            Title = "Đường Hầm Mùa Hạ Tập 2"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Price = 120000.0,
                            Quantity = 500,
                            Title = "Đường Hầm Mùa Hạ Tập 3"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Price = 120000.0,
                            Quantity = 2000,
                            Title = "Đường Hầm Mùa Hạ Tập 4"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Price = 120000.0,
                            Quantity = 1000,
                            Title = "Đường Hầm Mùa Hạ Tập 5"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Price = 120000.0,
                            Quantity = 1500,
                            Title = "Đường Hầm Mùa Hạ Tập 6"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Price = 120000.0,
                            Quantity = 500,
                            Title = "Đường Hầm Mùa Hạ Tập 7"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            Price = 120000.0,
                            Quantity = 2000,
                            Title = "Đường Hầm Mùa Hạ Tập 8"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Price = 120000.0,
                            Quantity = 1000,
                            Title = "Đường Hầm Mùa Hạ Tập 9"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 1,
                            Price = 120000.0,
                            Quantity = 1500,
                            Title = "Đường Hầm Mùa Hạ Tập 10"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 2,
                            Price = 130000.0,
                            Quantity = 500,
                            Title = "Dế Mèo Phiêu Lưu Ký Tập 1"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 2,
                            Price = 130000.0,
                            Quantity = 1000,
                            Title = "Dế Mèo Phiêu Lưu Ký Tập 2"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            Price = 130000.0,
                            Quantity = 1500,
                            Title = "Dế Mèo Phiêu Lưu Ký Tập 3"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 2,
                            Price = 130000.0,
                            Quantity = 2000,
                            Title = "Dế Mèo Phiêu Lưu Ký Tập 4"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 2,
                            Price = 130000.0,
                            Quantity = 500,
                            Title = "Dế Mèo Phiêu Lưu Ký Tập 5"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            Price = 130000.0,
                            Quantity = 1000,
                            Title = "Dế Mèo Phiêu Lưu Ký Tập 6"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 2,
                            Price = 130000.0,
                            Quantity = 1500,
                            Title = "Dế Mèo Phiêu Lưu Ký Tập 7"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 2,
                            Price = 130000.0,
                            Quantity = 2000,
                            Title = "Dế Mèo Phiêu Lưu Ký Tập 8"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 2,
                            Price = 130000.0,
                            Quantity = 500,
                            Title = "Dế Mèo Phiêu Lưu Ký Tập 9"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 2,
                            Price = 130000.0,
                            Quantity = 1000,
                            Title = "Dế Mèo Phiêu Lưu Ký Tập 10"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 3,
                            Price = 140000.0,
                            Quantity = 1500,
                            Title = "Hành Trình Đến Bắc Cực Tập 1"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 3,
                            Price = 140000.0,
                            Quantity = 2000,
                            Title = "Hành Trình Đến Bắc Cực Tập 2"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 3,
                            Price = 140000.0,
                            Quantity = 500,
                            Title = "Hành Trình Đến Bắc Cực Tập 3"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 3,
                            Price = 140000.0,
                            Quantity = 1000,
                            Title = "Hành Trình Đến Bắc Cực Tập 4"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 3,
                            Price = 140000.0,
                            Quantity = 1500,
                            Title = "Hành Trình Đến Bắc Cực Tập 5"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 3,
                            Price = 140000.0,
                            Quantity = 2000,
                            Title = "Hành Trình Đến Bắc Cực Tập 6"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 3,
                            Price = 140000.0,
                            Quantity = 500,
                            Title = "Hành Trình Đến Bắc Cực Tập 7"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 3,
                            Price = 140000.0,
                            Quantity = 1000,
                            Title = "Hành Trình Đến Bắc Cực Tập 8"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 3,
                            Price = 140000.0,
                            Quantity = 1500,
                            Title = "Hành Trình Đến Bắc Cực Tập 9"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 3,
                            Price = 140000.0,
                            Quantity = 2000,
                            Title = "Hành Trình Đến Bắc Cực Tập 10"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 4,
                            Price = 150000.0,
                            Quantity = 500,
                            Title = "Thế Giới Huyền Bí Tập 1"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 4,
                            Price = 150000.0,
                            Quantity = 1000,
                            Title = "Thế Giới Huyền Bí Tập 2"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 4,
                            Price = 150000.0,
                            Quantity = 1500,
                            Title = "Thế Giới Huyền Bí Tập 3"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 4,
                            Price = 150000.0,
                            Quantity = 2000,
                            Title = "Thế Giới Huyền Bí Tập 4"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 4,
                            Price = 150000.0,
                            Quantity = 500,
                            Title = "Thế Giới Huyền Bí Tập 5"
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 4,
                            Price = 150000.0,
                            Quantity = 1000,
                            Title = "Thế Giới Huyền Bí Tập 6"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 4,
                            Price = 150000.0,
                            Quantity = 1500,
                            Title = "Thế Giới Huyền Bí Tập 7"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 4,
                            Price = 150000.0,
                            Quantity = 2000,
                            Title = "Thế Giới Huyền Bí Tập 8"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 4,
                            Price = 150000.0,
                            Quantity = 500,
                            Title = "Thế Giới Huyền Bí Tập 9"
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 4,
                            Price = 150000.0,
                            Quantity = 1000,
                            Title = "Thế Giới Huyền Bí Tập 10"
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 5,
                            Price = 150000.0,
                            Quantity = 500,
                            Title = "Tên Của Bạn Là Tập 1"
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 5,
                            Price = 150000.0,
                            Quantity = 1000,
                            Title = "Tên Của Bạn Là Tập 2"
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 5,
                            Price = 150000.0,
                            Quantity = 1500,
                            Title = "Tên Của Bạn Là Tập 3"
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 5,
                            Price = 150000.0,
                            Quantity = 2000,
                            Title = "Tên Của Bạn Là Tập 4"
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 5,
                            Price = 150000.0,
                            Quantity = 500,
                            Title = "Tên Của Bạn Là Tập 5"
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 5,
                            Price = 150000.0,
                            Quantity = 1000,
                            Title = "Tên Của Bạn Là Tập 6"
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 5,
                            Price = 150000.0,
                            Quantity = 1500,
                            Title = "Tên Của Bạn Là Tập 7"
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 5,
                            Price = 150000.0,
                            Quantity = 2000,
                            Title = "Tên Của Bạn Là Tập 8"
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 5,
                            Price = 150000.0,
                            Quantity = 500,
                            Title = "Tên Của Bạn Là Tập 9"
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 5,
                            Price = 150000.0,
                            Quantity = 1000,
                            Title = "Tên Của Bạn Là Tập 10"
                        },
                        new
                        {
                            Id = 51,
                            AuthorId = 6,
                            Price = 160000.0,
                            Quantity = 1500,
                            Title = "Bên Kia Sông"
                        },
                        new
                        {
                            Id = 52,
                            AuthorId = 7,
                            Price = 170000.0,
                            Quantity = 500,
                            Title = "Lạc Trôi"
                        });
                });

            modelBuilder.Entity("Shared.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("UX_Role_RoleName");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Staff"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Seller"
                        });
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Email");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UX_User_UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared.Models.BillDetail", b =>
                {
                    b.HasOne("Shared.Models.Bill", "Bill")
                        .WithMany("BillDetails")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.BookSale", "BookSale")
                        .WithMany("BillDetails")
                        .HasForeignKey("BookSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("BookSale");
                });

            modelBuilder.Entity("Shared.Models.BookSale", b =>
                {
                    b.HasOne("Shared.Models.Author", "Author")
                        .WithMany("BookSales")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.HasOne("Shared.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shared.Models.Author", b =>
                {
                    b.Navigation("BookSales");
                });

            modelBuilder.Entity("Shared.Models.Bill", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("Shared.Models.BookSale", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("Shared.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
